services:
  - type: web
    name: mpesa-ecommerce
    env: python
    runtime: python-3.11.4
    buildCommand: "./build.sh"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT Ecoweb.wsgi:application"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mpesa-ecommerce-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "mpesa-integrated-django-ecommerce.onrender.com,*.onrender.com,127.0.0.1,localhost"
      - key: MPESA_CONSUMER_KEY
        sync: false
      - key: MPESA_CONSUMER_SECRET
        sync: false
      - key: MPESA_PASSKEY
        sync: false
      - key: MPESA_SHORTCODE
        value: "174379"
      - key: MPESA_IS_SANDBOX
        value: "False"
      - key: MPESA_TEST_MODE
        value: "False"
      - key: PYTHONPATH
        value: "/opt/render/project/src"

databases:
  - name: mpesa-ecommerce-db
    databaseName: mpesa_ecommerce
    user: mpesa_user